[package]
name = "missile-carnival"
version = "0.1.0"
authors = ["Andrew Lee <quabeeb@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.5"
rand = "0.7.3"
nalgebra = "0.20"
ncollide2d = "0.22"
nphysics2d = "0.14"
